apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibetown.fullname" . }}
  labels:
    {{- include "vibetown.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vibetown.selectorLabels" . | nindent 4 }}
