version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /engine
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: /server
    schedule:
      interval: weekly
    groups:
      rust-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      npm-deps:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: monthly
