apiVersion: v1
kind: Service
metadata:
  name: vibetown
  # namespace set by kustomization.yaml or overlay
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vibetown
